GET http://localhost:5000/subrek

###

GET http://localhost:5000/subrek/60912a697870c410e84cd8ce

### 

POST http://localhost:5000/subrek
Content-type: application/json

{
    "name": "Yogi",
    "subrek": "Tipe-X"
}

###

DELETE http://localhost:5000/subrek/60912ac27870c410e84cd8cf

###

PATCH http://localhost:5000/subrek/60912a697870c410e84cd8ce
Content-type: application/json

{
    "name": "Namaku bukan Ilham"
}